sudo: false
language: python
cache: pip

matrix:
  include:
  - python: "2.7"
    env: DEPS="wheel setuptools pip"
  - python: "3.4"
    env: DEPS="wheel setuptools pip"
  - python: "3.5"
    env: DEPS="wheel setuptools pip"
  - python: "3.6"
    env: DEPS="wheel setuptools pip"
  - python: "pypy"
    env: DEPS="wheel setuptools pip"
  - python: "pypy3"
    env: DEPS="wheel setuptools pip"


before_install:
- pip install -U $DEPS

install:
- pip install .[dev,test]

script:
- coverage run --source=pronto -m unittest discover -v
- coverage xml --include "pronto/*"

after_success:
- codecov
- python-codacy-coverage -r coverage.xml

before_deploy:
- python setup.py check -rms

deploy:
- provider: pypi
  user: althonos
  password:
    secure: tOxmKL2WfIajsSao4rVau9xLehIqfpKOm9SCwUlGREJas/D+yFYcltdamVa/kpc2PgHcmQBJxkZzEEDsAiZunm/435qWR2T01B2zB00JdtfWvnoCWEEzg/SEsy/0yS6m666P3vbdSvtfHByaavzPf5RE3ooBwsbKt3OKgS3fs91zFZwJZU6zATpBC6pzwhbt6PZeYzmZnk2AkRl8O2abPh8iHz1DGxJ3baY3ObG289W5Dp9a3sr9PVkXvLCMe04JeORTlPt43hnAy6PpnN8FSgKKLdTiMeqRcctZdH8Y90EIW8nWWoqaokNVLepxDDtf3ouy57DNyZu1FNZDlsQd7aYyUrydy7UIrMa33L7ai0hRcvKQI1ymRbO3W4opOPDcORulvYGUNLeVU886lvuLavlJ+otZClRBPV3EuO0k2eslAvwiTF8DBjB9HPuF3ZtkBgnDH7ubU1hoMi6MQvbjVThI0J7uyTVNmnS8r9/Yv02TsTl+IBHzhE3Sb8z2ZNF/Ip5UU5rbcmmvA/euShL2A+Eb0hhe/Fen3fVROl/cwcGIbkEXTurzc5xfyoLs76VOxr+HvYqA4DzxvDwhhvQSk0PTymO5T5WRj4PYbmkHeevVCsH8unva27u1CeKhVYIrWyvXwDhIK11mLzWKT2SAEVypil8YUcQpROR8vJP2yA4=
  distributions: sdist bdist_wheel
  on:
    python: '3.6'
    tags: true
    repo: althonos/pronto
  server: https://upload.pypi.org/legacy/

notifications:
  email:
  - althonosdev@gmail.com
